
version: 2


models:
    - name: google_forms
      description: ""
      # tests:
      # - dbt_utils.unique_combination_of_columns:
      #     combination_of_columns:
      #       - respondent_email
      #       - last_submitted
      #       - question_id
