name: 'project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"

models:
  +persist_docs:
    relation: true
    columns: true
  project:
    analytics_middle_tier:
      +materialized: table
      +tags: amt
      +schema: analytics_middle_tier
    edfi:
      +materialized: table
      +schema: edfi
      +tags: edfi
      +labels:
          edfi_version: "5_3"
