
version: 2

models:
  - name: student_attendance_fact
    description: >
      Used for looking at a student's attendance per day. This fact table provides a row
      for each instructional day the student holds an enrollment up to the previous date.
    columns:
      - name: student_key
        tests:
          - relationships:
              to: ref('student_local_education_agency_dim')
              field: student_key
      - name: "(student_key || '-' || school_key)"
        tests:
          - relationships:
              to: ref('student_school_dim')
              field: student_school_key

  - name: stg_student_attendance_fact
    description: >
      Staging version of the attendance fact table that joins on the date dim and student dim
      to add contextual information.
