version: 2

sources:
    - name: raw_sources
      schema: |
        {%- if  target.name == "dev" -%} dev_raw_sources
        {%- else -%} prod_raw_sources
        {%- endif -%}
      tables:
        - name: edfi_assessments
        - name: edfi_assessments_deletes
        - name: edfi_calendars
        - name: edfi_calendars_deletes
        - name: edfi_calendar_dates
        - name: edfi_calendar_dates_deletes
        - name: edfi_courses
        - name: edfi_courses_deletes
        - name: edfi_course_offerings
        - name: edfi_course_offerings_deletes
        - name: edfi_discipline_actions
        - name: edfi_discipline_actions_deletes
        - name: edfi_discipline_incidents
        - name: edfi_discipline_incident_deletes
        - name: edfi_grading_periods
        - name: edfi_grading_periods_deletes
        - name: edfi_grading_period_descriptors
        - name: edfi_grades
        - name: edfi_grades_deletes
        - name: edfi_local_education_agencies
        - name: edfi_local_education_agencies_deletes
        - name: edfi_objective_assessments
        - name: edfi_objective_assessments_deletes
        - name: edfi_parents
        - name: edfi_parents_deletes
        - name: edfi_schools
        - name: edfi_schools_deletes
        - name: edfi_school_year_types
        - name: edfi_sections
        - name: edfi_sections_deletes
        - name: edfi_sessions
        - name: edfi_sessions_deletes
        - name: edfi_staffs
        - name: edfi_staffs_deletes
        - name: edfi_staff_discipline_incident_associations
        - name: edfi_staff_discipline_incident_associations_deletes
        - name: edfi_staff_education_organization_assignment_associations
        - name: edfi_staff_education_organization_assignment_associations_deletes
        - name: edfi_staff_section_associations
        - name: edfi_staff_section_associations_deletes
        - name: edfi_students
        - name: edfi_students_deletes
        - name: edfi_student_assessments
        - name: edfi_student_assessments_deletes
        - name: edfi_student_discipline_incident_associations
        - name: edfi_student_discipline_incident_associations_deletes
        - name: edfi_student_education_organization_associations
        - name: edfi_student_education_organization_associations_deletes
        - name: edfi_student_parent_associations
        - name: edfi_student_parent_associations_deletes
        - name: edfi_student_school_associations
        - name: edfi_student_school_associations_deletes
        - name: edfi_student_school_attendance_events
        - name: edfi_student_school_attendance_events_deletes
        - name: edfi_student_section_associations
        - name: edfi_student_section_associations_deletes
        - name: edfi_student_section_attendance_events
        - name: edfi_student_section_attendance_events_deletes
        - name: edfi_cohort_type_descriptors
        - name: edfi_cohort_type_descriptors_deletes
        - name: edfi_disability_descriptors
        - name: edfi_disability_descriptors_deletes
        - name: edfi_language_descriptors
        - name: edfi_language_descriptors_deletes
        - name: edfi_language_use_descriptors
        - name: edfi_language_use_descriptors_deletes
        - name: edfi_race_descriptors
        - name: edfi_race_descriptors_deletes
