version: 2

sources:
    - name: raw_sources
      schema: |
        {%- if  target.name == "dev" -%} dev_raw_sources
        {%- else -%} prod_raw_sources
        {%- endif -%}
      tables:
        - name: edfi_calendars
        - name: edfi_calendar_dates
        - name: edfi_courses
        - name: edfi_course_offerings
        - name: edfi_grading_periods
        - name: edfi_local_education_agencies
        - name: edfi_parents
        - name: edfi_schools
        - name: edfi_school_year_types
        - name: edfi_sections
        - name: edfi_sessions
        - name: edfi_staffs
        - name: edfi_staff_education_organization_assignment_associations
        - name: edfi_staff_section_associations
        - name: edfi_students
        - name: edfi_student_education_organization_associations
        - name: edfi_student_parent_associations
        - name: edfi_student_school_associations
        - name: edfi_student_school_attendance_events
        - name: edfi_student_section_associations
        - name: edfi_student_section_attendance_events
        - name: edfi_cohort_type_descriptors
        - name: edfi_disability_descriptors
        - name: edfi_language_descriptors
        - name: edfi_language_use_descriptors
        - name: edfi_race_descriptors
